const products = [
    {
        id: 1,
        name: "Smart TV with led",
        price: 500000,
        avg_product_rating: 4,
        num_of_raters: 20,
        MainCategory:"Electronics",
        category: "Television & Video",
        subCategory: "Televisions",
        brand: "LED",
        size: "",
        order: 13,
        sold: 10,
        percentageDeecrease: 15,
        imgUrl: "",
        additionalDetails: ""        
    },
    {
        id: 2,
        name: "Full flash TV",
        price: 1300000,
        avg_product_rating: 4,
        num_of_raters: 10,
        MainCategory:"Electronics",
        category: "Television & Video",
        subCategory: "Televisions",
        brand: "LED",
        size: "",
        order: 13,
        sold: 10,
        percentageDeecrease: 15,
        imgUrl: "",
        additionalDetails: ""        
    },
    {
        id: 3,
        name: "Samsung TV",
        price: 400000,
        avg_product_rating: 4,
        num_of_raters: 140,
        MainCategory:"Electronics",
        category: "Television & Video",
        subCategory: "Televisions",
        brand: "Samsung",
        size: "",
        order: 13,
        sold: 10,
        percentageDeecrease: 15,
        imgUrl: "",
        additionalDetails: ""        
    },
    {
        id: 4,
        name: "Full flash led light",
        price: 400000,
        avg_product_rating: 4,
        num_of_raters: 140,
        MainCategory:"Electronics",
        category: "Television & Video",
        subCategory: "Televisions",
        brand: "LED",
        size: "",
        order: 13,
        sold: 10,
        percentageDeecrease: 15,
        imgUrl: "",
        additionalDetails: ""        
    },
    {
        id: 5,
        name: "Full flash led light",
        price: 400000,
        avg_product_rating: 4,
        num_of_raters: 140,
        MainCategory:"Electronics",
        category: "Television & Video",
        subCategory: "Televisions",
        brand: "LED",
        size: "",
        order: 13,
        sold: 10,
        percentageDeecrease: 15,
        imgUrl: "",
        additionalDetails: ""        
    },
    {
        id: 6,
        name: "Full flash led light",
        price: 400000,
        avg_product_rating: 4,
        num_of_raters: 140,
        MainCategory:"Electronics",
        category: "Television & Video",
        subCategory: "Televisions",
        brand: "LED",
        size: "",
        order: 13,
        sold: 10,
        percentageDeecrease: 15,
        imgUrl: "",
        additionalDetails: ""        
    },
    {
        id: 7,
        name: "Full flash led light",
        price: 400000,
        avg_product_rating: 4,
        num_of_raters: 140,
        MainCategory:"Electronics",
        category: "Television & Video",
        subCategory: "Televisions",
        brand: "LED",
        size: "",
        order: 13,
        sold: 10,
        percentageDeecrease: 15,
        imgUrl: "",
        additionalDetails: ""        
    }
];
export default products;